export const experiences = [
  {
    company: "LuckyCrush",
    link: "https://www.luckycrush.live/",
    role: "Senior Software Engineer",
    dates: "12.2022 - Ongoing",
    info: "LuckyCrush is a platform to make users have 1-1 videocalls with random people.",
    responsibilities: [
      "Created the mobile app from scratch using React Native",
      "Created Gitlab pipeline to auto build and auto submit from master to stores via Eas Build",
      "Implemented videocall feature using Voyage OpenTok library",
      "Implemented In-app Purchases for Play Store and App Store",
      "Added strings in Lokalize to support multi languages",
      "Managed both stores",
    ],
    technologies: [
      "React Native",
      "Expo",
      "Typescript",
      "Javascript",
      "Styled Components",
      "Voyage Opentok",
      "Gitlab pipelines"
    ],
  },
  {
    company: "Avantstay",
    link: "https://avantstay.com/",
    role: "Senior Software Engineer",
    dates: "04.2022 - 12.2022",
    info: "AvantStay is a premier next-generation hospitality platform for short-term rental experiences in USA.",
    responsibilities: [
      "Worked in the mobile app project (cross-platform)",
      "Created new features and improved existing features using React Native (Expo bare-flow)",
      "Managed both applications for IOS and Android",
      "Published new releases",
      "Managed stores",
      "Fixed bugs by over-the-air updates",
      "Writed unit tests",
      "Reviewed Front End mobile code",
    ],
    technologies: [
      "React Native",
      "Expo",
      "Typescript",
      "Javascript",
      "Jest",
      "GraphQL",
      "Styled Components",
    ],
  },
  {
    company: "VMware Cloud Services (CSP)",
    link: "https://console.cloud.vmware.com",
    role: "Front-end Engineer",
    dates: "04.2021 - 04.2022",
    info: "VMware Cloud Services Platform is the plaform for services that enable you to integrate, manage, and secure applications on cloud resources. These services work for any cloud service using VMware and can help you centralize the management and maintenance of hybrid or multi-cloud environments.",
    responsibilities: [
      "Worked with an engineering team of 20 members",
      "Created new features and improved existing features in CSP used latest Angular",
      "Writed unit tests using Karma",
      "Writed E2E tests using Protractor",
      "Reviewed Front End code",
      "Monitored pipelines in Jenkins",
      "Contributed to open source Vmware Project for Angular Components (VMware ngx components)",
      "Worked on Accessibility issues and improvements for the platform",
    ],
    technologies: [
      "Angular",
      "Typescript",
      "Javascript",
      "Clarity Design",
      "Karma",
      "Protractor",
      "Jenkins",
      "ARIA",
      "RxJS",
    ],
  },
  {
    company: "Symanto",
    link: "https://www.symanto.com",
    role: "Front-end Engineer",
    dates: "01.2020 - 02.2021",
    info: "Symanto has its own product which is an AI-based solution for customers to analyze their plain data and get fancy results. Customers can upload their own data, also they can create collectors to collect data from other websites. After the data is collected and analyzed, customers can use the charts and tables to understand what categories/topics are the most popular, whether they include positive sentiments or negative sentiments, compare topics and brands, see timelines of data, etc. In addition, to increase the analysis, they can interact with texts to select words in order to create and edit topics and sentiments with them and rerun the project again with improved dictionaries. Management company users can edit customers, projects, dictionaries, clusters, crawlers, etc. They can improve dictionary qualities with inline-editing tools, miller columns, token-based tables etc.",
    responsibilities: [
      "Worked in scrum with an engineering team of 15 members",
      "Created Insights Platform in Angular 8 - 11",
      "Used Angular features with RxJs for core data services in Insights Platform",
      "Improved Management Platform in Angular 7 - 10",
      "Used Redux for state management in Management Platform",
      "Used Angular Material, Bootstrap for design components",
      "Reviewed Front End code",
      "Contributed to .NET APIs changes when needed",
    ],
    technologies: [
      "Angular",
      "Typescript",
      "Azure DevOps",
      "ChartJS",
      "Stripe",
      "HTML5",
      "SCSS",
      "InVision",
      ".NET",
      "RxJS",
      "NgRx",
      "Bootstrap",
      "Angular Material",
    ],
  },
  {
    company: "Bus2Go",
    link: "https://www.bus2go.mk",
    role: "Full Stack Engineer",
    dates: "09.2017 - 02.2021",
    info: "Bus2Go is a platform where customers can purchase bus tickets online by using 3D secure payment in the web or in the mobile app and use the QR codes for their tickets. Bus drivers can validate tickets by using the mobile app and camera of their phones to scan QR codes. Bus companies can also CRUD routes, timetables, prices, etc",
    responsibilities: [
      "Worked with an engineering team of 5 members",
      "Created a mobile app in Ionic Framework 3",
      "Created a web app in Angular 6 - 8",
      "Created an Admin Panel in Angular 8",
      "Contributed to API creation, in .NET Core Framework",
      "Created a payment project in C# which deals with payments of HalkBank 3D secure pay",
      "Used Angular Material, Bootstrap, Nebular for design components",
    ],
    technologies: [
      "Angular",
      "Typescript",
      "Javascript",
      "Ionic",
      "HTML5",
      "SCSS",
      "Adobe XD",
      ".NET Core",
      "RxJS",
      "NgRx",
      "Bootstrap",
      "Angular Material",
      "Microsoft SQL Server",
    ],
  },
];

const getExperiences = (_, res) => {
  res.status(200).json(experiences);
};

export default getExperiences;
