export const experiences = [
  {
    company: "Avantstay",
    link: "https://avantstay.com/",
    role: "Senior Software Engineer",
    dates: "04.2022 - Ongoing",
    info: "AvantStay is a premier next-generation hospitality platform for short-term rental experiences in USA.",
    responsibilities: [
      "Working in the mobile app project (cross-platform)",
      "Creating new features and improving existing features in mobile app using React Native (Expo bare-flow)",
      "Managing both applications for IOS and Android",
      "Publishing new releases",
      "Managing stores",
      "Fixing important things by over-the-air updates",
      "Writing unit tests",
      "Reviewing Front End mobile code",
    ],
    technologies: [
      "React Native",
      "Expo",
      "Typescript",
      "Javascript",
      "Jest",
      "GraphQL",
      "Styled Components",
    ],
  },
  {
    company: "VMware Cloud Services (CSP)",
    link: "https://console.cloud.vmware.com",
    role: "Front-end Engineer",
    dates: "04.2021 - 04.2022",
    info: "VMware Cloud Services Platform is the plaform for services that enable you to integrate, manage, and secure applications on cloud resources. These services work for any cloud service using VMware and can help you centralize the management and maintenance of hybrid or multi-cloud environments.",
    responsibilities: [
      "Working with an engineering team of 20 members in Front End and hundreds of people to communicate (BE, Testers, Designers, Managers, Accessability team, Other teams)",
      "Creating new features and improving existing features in CSP using latest Angular",
      "Writing unit tests for my changes to cover all cases using Karma",
      "Writing E2E tests using Protractor",
      "Reviewing Front End code",
      "Monitoring pipelines in Jenkins",
      "Contributing to open source Vmware Project for Angular Components (VMware ngx components)",
      "Working on Accessibility issues and improvements for the platform",
    ],
    technologies: [
      "Angular",
      "Typescript",
      "Javascript",
      "Clarity Design",
      "Karma",
      "Protractor",
      "Jenkins",
      "ARIA",
      "RxJS",
    ],
  },
  {
    company: "Musala Soft",
    link: "https://www.musala.com",
    role: "Software Engineer",
    dates: "02.2021 - 04.2022",
    info: "Musala Soft is a leading company known for its solutions to many internationally well-known clients.",
    responsibilities: [
      "Extending skills area",
      "Learning, designing, and implementing solutions with new technologies",
      "Sharing knowledge in the team",
      "Working effectively for VMware",
    ],
    technologies: [
      "Figma",
      "Javascript",
      "React",
      "NextJS",
      "Svelte",
      "React Native",
      "HTML5",
      "CSS3",
      "GraphQL",
      "ExpressJS",
      "MongoDB",
    ],
  },
  {
    company: "Symanto",
    link: "https://www.symanto.com",
    role: "Front-end Engineer",
    dates: "01.2020 - 02.2021",
    info: "Symanto has its own product which is an AI-based solution for customers to analyze their plain data and get fancy results. Customers can upload their own data, also they can create collectors to collect data from other websites. After the data is collected and analyzed, customers can use the charts and tables to understand what categories/topics are the most popular, whether they include positive sentiments or negative sentiments, compare topics and brands, see timelines of data, etc. In addition, to increase the analysis, they can interact with texts to select words in order to create and edit topics and sentiments with them and rerun the project again with improved dictionaries. Management company users can edit customers, projects, dictionaries, clusters, crawlers, etc. They can improve dictionary qualities with inline-editing tools, miller columns, token-based tables etc.",
    responsibilities: [
      "Working in scrum with an engineering team of 15 members",
      "Creating Insights Platform in Angular 8 - 11",
      "Using Angular features with RxJs for core data services in Insights Platform",
      "Improving Management Platform in Angular 7 - 10",
      "Using Redux for state management in Management Platform",
      "Using Angular Material, Bootstrap for design components",
      "Reviewing Front End code",
      "Contributing to .NET APIs changes when needed",
    ],
    technologies: [
      "Angular",
      "Typescript",
      "Azure DevOps",
      "ChartJS",
      "Stripe",
      "HTML5",
      "SCSS",
      "InVision",
      ".NET",
      "RxJS",
      "NgRx",
      "Bootstrap",
      "Angular Material",
    ],
  },
  {
    company: "Technoperia",
    link: "https://www.technoperia.com",
    role: "Full Stack Engineer",
    dates: "09.2017 - 02.2021",
    info: "Technoperia is a company working in software solutions and has its own product named Bus2Go. Bus2Go is a platform where customers can purchase bus tickets online by using 3D secure payment in the web or in the mobile app and use the QR codes for their tickets. Bus drivers can validate tickets by using the mobile app and camera of their phones to scan QR codes. Bus companies can also CRUD routes, timetables, prices, etc. Last year, I worked for Symanto as a contractor.",
    responsibilities: [
      "Working with an engineering team of 5 members",
      "Creating a mobile app in Ionic Framework 3",
      "Creating a web app in Angular 6 - 8",
      "Creating an Admin Panel in Angular 8",
      "Contributing to API creation, in .NET Core Framework",
      "Creating a payment project in C# which deals with payments of HalkBank 3D secure pay",
      "Using Angular Material, Bootstrap, Nebular for design components",
    ],
    technologies: [
      "Angular",
      "Typescript",
      "Javascript",
      "Ionic",
      "HTML5",
      "SCSS",
      "Adobe XD",
      ".NET Core",
      "RxJS",
      "NgRx",
      "Bootstrap",
      "Angular Material",
      "Microsoft SQL Server",
    ],
  },
];

const getExperiences = (_, res) => {
  res.status(200).json(experiences);
};

export default getExperiences;
