export const projects = [
  {
    name: "Stanislove",
    links: [
      "https://www.stanislove.mk",
      "https://apps.apple.com/mk/app/stanislove/id1608443434",
      "https://play.google.com/store/apps/details?id=com.ibrahimaliu.stanislove",
    ],
    info: "Stanislove is a cross platform mobile app for finding you the best houses, apartments, villas, shops, lands for rent and for purchase in North Macedonia.",
    responsibilities: [
      "Designed the designs using Figma",
      "Created a Database using MongoDB",
      "Created an API using NodeJS, GraphQL, and Apollo Server",
      "Created a mobile app using React Native with Expo",
      "Created a web app using NextJs",
      "Supported photo uploads of properties using Amazon S3 service",
      "Resized and compressed photo uploads",
      "Supported in memory cache using Apollo Client",
      "Used Google Maps for properties, geocoded and reverse geocoded from address to geolocations",
      "Supported multi languages using i18n",
      "Created a logo, assets, online content",
      "Published on Play Store",
      "Published on App Store",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "Figma",
      "Javascript",
      "Typescript",
      "React Native",
      "Expo",
      "Mongoose",
      "MongoDB",
      "GraphQL",
      "Apollo Server/Client",
      "Amazon S3 service",
      "NodeJs",
      "ExpressJs",
    ],
  },
  {
    name: "Antep Baklava",
    links: ["https://www.antepbaklava.mk"],
    info: "Antep Baklava is a sweet company that has 20+ shops in more than 15 cities and multiple countries. This project contains a landing page and online shopping experience for users, and admin panel for company users. Customers can buy baklava online. Company users can install a PWA to get notifications and better user experience.",
    responsibilities: [
      "Designed pages in Figma",
      "Created a landing page and a dashboard using NextJs",
      "Created an API in ExpressJS and GraphQL",
      "Created a Database using Mongoose and MongoDB",
      "Created the platform as Progressive Web App",
      "Sended notifications to company users after purchases",
      "Created animations using Framer Motion",
      "Supported mutli languages",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "React",
      "NextJs",
      "Javascript",
      "Typescript",
      "Svelte",
      "MongoDB",
      "Mongoose",
      "GraphQL",
      "NodeJs",
      "ExpressJs",
      "React Native",
    ],
  },
  {
    name: "UrbanGym Admin Panel",
    links: [],
    info: "UrbanGym Admin Panel is a platform designed for this gym to store their customers' subscriptions",
    responsibilities: [
      "Implemented it in React",
      "Used Firebase as Backend",
      "Maked responsive for both mobile and web screens",
      "Created it as PWA",
      "Supported dynamic QR code and page generations for clients to check their subscriptions (day left, personal info, etc)",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "Typescript",
      "React",
      "Tailwind",
      "Firebase"
    ],
  },
  {
    name: "TechStack",
    links: ["https://technologystack.netlify.app"],
    info: "TechStack is a project where people can share the best resources about technologies, and also for starters, where they can find the best links to start learning a technology.",
    responsibilities: [
      "Created an API in ExpressJS and GraphQL",
      "Created a Database using MongoDB",
      "Created a Web App using Svelte",
      "Created a Mobile App using React Native with Expo",
      "Designed the front-end using Figma",
      "Deployed the website to Netlify",
      "Deployed the API to Heroku",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "Figma",
      "Javascript",
      "Typescript",
      "Svelte",
      "MongoDB",
      "Mongoose",
      "GraphQL",
      "React Native",
    ],
  },
  {
    name: "Weather Matters",
    links: ["https://ibrahim94ali.github.io/weather-matters"],
    info: "Weather Matters is a web application which shows the current and forecast weather information of several cities. Data is fetched from a third-party API.",
    responsibilities: [
      "Designed UI/UX",
      "Implemented it in Angular 11",
      "Maked responsive for both mobile and computer screens",
      "Visualized data using ChartJs",
      "Writed automated tests",
      "Deployed the app to Github Pages",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "Figma",
      "Typescript",
      "Angular",
      "Angular Material",
      "Jasmine",
      "Karma",
      "Protractor",
      "ChartJS",
    ],
  },
  {
    name: "FX Calculator",
    links: ["https://github.com/ibrahim94ali/Fx-Calculator"],
    info: "It is a simple mobile application with ready API to convert currencies in real time. A user can convert a specific value of selected base currency in 25 different currencies in real time.",
    responsibilities: [
      "Designed UI/UX",
      "Designed a logo",
      "Implemented it in Ionic 4",
      "Tested the app",
      "Writed automated tests",
      "Delivered the app",
    ],
    technologies: [
      "Adobe XD",
      "HTML5",
      "SCSS",
      "NgRx",
      "RxJs",
      "Ionic",
      "Typescript",
    ],
  },
  {
    name: "Bee Safe",
    links: ["https://github.com/ibrahim94ali/BeeSafe"],
    info: "Bee Safe is a cross platform mobile app where users can manage and store their passwords safely. Users can enter the app with the fingerprint data of the phones or with a pin, generate strong passwords, store each account credentials, copy the password to clipboard for a limited time and use it in other accounts. Users can choose to store all their data locally and transfer to another phone by synchronizing data with the server. Server flushes all data after 24 hours.",
    responsibilities: [
      "Designed UI/UX",
      "Designed Logo",
      "Created mobile application in Ionic",
      "Used KintoJS for synchronization",
      "Generated secure passwords",
      "Used federprint login",
      "Tested the app",
      "Delivered the app",
    ],
    technologies: [
      "Adobe XD",
      "HTML5",
      "SCSS",
      "Ionic",
      "Typescript",
      "Javascript",
      "KintoJS",
    ],
  },
  {
    name: "List It Yourself",
    links: ["https://github.com/ibrahim94ali/ListItYourself"],
    info: "List It Yourself is a cross platform mobile application where users can login with their accounts to create calendar events and to-do lists privately or in groups. They get notifications when an event is about to happen and when somebody in group events/to-do lists updates the event/to-do list.",
    responsibilities: [
      "Designed UI/UX",
      "Designed a Logo",
      "Created mobile application in Ionic",
      "Created Firebase application for back-end and real-time database",
      "Designed NoSQL structure",
      "Tested the app",
      "Delivered the app",
    ],
    technologies: [
      "HTML5",
      "SCSS",
      "Ionic",
      "Typescript",
      "Firebase",
      "Jira",
      "BitBucket",
    ],
  },
  {
    name: "Prediction App for Return Items in Sales",
    links: ["https://github.com/ibrahim94ali/lfd_term_project"],
    info: "This is a solution for a company where they can enter a sale and see if this sale will be returned back or not. The aim of this solution is to cut costs of the company for returns. Our solution uses annual data of sales and develops a system using Machine Learning models to predict the return of each sale in the future.",
    responsibilities: [
      "Getted big data from Kaggle",
      "Explored data",
      "Cleaned data",
      "Used Machine Learning models (Linear-Regression, Logistic Regression, Randomforest)",
      "Created own solution",
      "Runned trained data to train our model",
      "Runned test data to append our predictions",
      "Improved accuracy",
    ],
    technologies: ["Python", "NumPy", "Scikit-learn", "Kaggle"],
  },
];

const getProjects = (_, res) => {
  res.status(200).json(projects);
};

export default getProjects;
