export const projects = [
  {
    name: "Stanislove",
    links: [
      {
        label: "Google Play",
        link: "https://play.google.com/store/apps/details?id=com.ibrahimaliu.stanislove",
      },
      {
        label: "App Store",
        link: "https://apps.apple.com/mk/app/stanislove/id1608443434",
      },
      {
        label: "Web App",
        link: "https://stanislove-web.vercel.app/",
      },
    ],
    info: "Stanislove is a cross-platform mobile application that helps users find the best houses, apartments, villas, shops, and land for rent or purchase in North Macedonia.",
    responsibilities: [
      "Designed and prototyped the user interface using Figma.",
      "Developed a robust database using MongoDB.",
      "Built a scalable API using Node.js, GraphQL, and Apollo Server.",
      "Developed the mobile application using React Native with Expo.",
      "Created a responsive web application using Next.js.",
      "Implemented secure property image uploads using Amazon S3.",
      "Optimized images by resizing and compressing uploads.",
      "Integrated in-memory caching with Apollo Client for improved performance.",
      "Implemented geolocation features, including address-to-coordinates conversion, using Google Maps API.",
      "Developed multilingual support using i18n.",
      "Designed the application's branding, including the logo and digital assets.",
      "Published the application on Google Play Store and Apple App Store.",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "Figma",
      "Javascript",
      "Typescript",
      "React Native",
      "Expo",
      "Mongoose",
      "MongoDB",
      "GraphQL",
      "Apollo Server/Client",
      "Amazon S3 service",
      "NodeJs",
      "ExpressJs",
    ],
  },
  {
    name: "Antep Baklava",
    links: [
      {
        label: "Web App",
        link: "https://www.antepbaklava.mk",
      },
    ],
    info: "Antep Baklava is a renowned confectionery company with 20+ stores across 15+ cities and multiple countries. This project includes a landing page, an online shopping experience for customers, and an admin panel for company users.",
    responsibilities: [
      "Designed the landing page and admin panel using Figma.",
      "Developed a fully responsive landing page and dashboard using Next.js.",
      "Built a secure API using Express.js and GraphQL.",
      "Designed and implemented a scalable database using MongoDB with Mongoose.",
      "Developed the platform as a Progressive Web Application (PWA) for enhanced performance and offline support.",
      "Implemented real-time notifications for company users upon purchases.",
      "Created smooth, engaging animations using Framer Motion.",
      "Enabled multilingual support for a global user base.",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "React",
      "NextJs",
      "Javascript",
      "Typescript",
      "Svelte",
      "MongoDB",
      "Mongoose",
      "GraphQL",
      "NodeJs",
      "ExpressJs",
      "React Native",
    ],
  },
  {
    name: "UrbanGym Admin Panel",
    links: [],
    info: "UrbanGym Admin Panel is a management platform designed to store and track gym membership subscriptions efficiently.",
    responsibilities: [
      "Developed the application using React.",
      "Implemented Firebase as the backend for authentication and data storage.",
      "Designed a fully responsive UI for both mobile and desktop users.",
      "Built the platform as a Progressive Web Application (PWA).",
      "Developed dynamic QR code generation for clients to check their remaining subscription days and personal information.",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "Typescript",
      "React",
      "Tailwind",
      "Firebase",
    ],
  },
  {
    name: "TechStack",
    links: [
      {
        label: "Web App",
        link: "https://technologystack.netlify.app",
      },
    ],
    info: "TechStack is a knowledge-sharing platform where users can discover and contribute the best resources for learning various technologies.",
    responsibilities: [
      "Developed a RESTful API using Express.js and GraphQL.",
      "Designed and implemented a MongoDB-based database.",
      "Built a dynamic web application using Svelte.",
      "Developed a mobile application using React Native with Expo.",
      "Designed an intuitive front-end experience using Figma.",
      "Deployed the web application to Netlify for seamless hosting.",
      "Hosted the API on Heroku for scalability.",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "Figma",
      "Javascript",
      "Typescript",
      "Svelte",
      "MongoDB",
      "Mongoose",
      "GraphQL",
      "React Native",
    ],
  },
  {
    name: "Weather Matters",
    links: [
      {
        label: "Web App",
        link: "https://ibrahim94ali.github.io/weather-matters",
      },
    ],
    info: "Weather Matters is a web application that provides real-time and forecast weather data for multiple cities, sourced from a third-party API.",
    responsibilities: [
      "Designed a user-friendly UI/UX experience.",
      "Developed the application using Angular 11.",
      "Ensured a fully responsive design for both mobile and desktop users.",
      "Integrated data visualization using Chart.js.",
      "Implemented automated testing for quality assurance.",
      "Deployed the application on GitHub Pages for easy access.",
    ],
    technologies: [
      "CSS3",
      "HTML5",
      "Figma",
      "Typescript",
      "Angular",
      "Angular Material",
      "Jasmine",
      "Karma",
      "Protractor",
      "ChartJS",
    ],
  },
  {
    name: "FX Calculator",
    links: [
      {
        label: "Repository",
        link: "https://github.com/ibrahim94ali/Fx-Calculator",
      },
    ],
    info: "A lightweight mobile application that enables real-time currency conversion across 25 different currencies using a ready-made API.",
    responsibilities: [
      "Designed an intuitive UI/UX experience.",
      "Created a logo and branding assets.",
      "Developed the application using Ionic 4.",
      "Conducted thorough testing to ensure accuracy and stability.",
      "Implemented automated test scripts for reliability.",
      "Successfully delivered the application for end users.",
    ],
    technologies: [
      "Adobe XD",
      "HTML5",
      "SCSS",
      "NgRx",
      "RxJs",
      "Ionic",
      "Typescript",
    ],
  },
  {
    name: "Bee Safe",
    links: [
      {
        label: "Repository",
        link: "https://github.com/ibrahim94ali/BeeSafe",
      },
    ],
    info: "Bee Safe is a secure cross-platform password manager that allows users to store and manage their credentials safely. Users can log in via fingerprint authentication or PIN, generate strong passwords, and securely transfer data between devices.",
    responsibilities: [
      "Designed a modern UI/UX experience.",
      "Developed the application logo and branding.",
      "Built the mobile application using Ionic.",
      "Implemented data synchronization using Kinto.js.",
      "Integrated secure password generation features.",
      "Developed biometric authentication via fingerprint login.",
      "Conducted extensive testing to ensure security and reliability.",
      "Successfully deployed and delivered the application.",
    ],
    technologies: [
      "Adobe XD",
      "HTML5",
      "SCSS",
      "Ionic",
      "Typescript",
      "Javascript",
      "KintoJS",
    ],
  },
  {
    name: "List It Yourself",
    links: [
      {
        label: "Repository",
        link: "https://github.com/ibrahim94ali/ListItYourself",
      },
    ],

    info: "List It Yourself is a cross-platform productivity application that enables users to create and manage calendar events and to-do lists privately or in shared groups. Users receive real-time notifications for upcoming events and updates made by group members.",
    responsibilities: [
      "Designed a user-friendly UI/UX experience.",
      "Created a distinctive logo and branding.",
      "Developed the mobile application using Ionic.",
      "Implemented Firebase as the backend with a real-time NoSQL database.",
      "Designed a scalable NoSQL structure for efficient data management.",
      "Conducted rigorous testing to ensure app stability.",
      "Successfully delivered the application to end users.",
    ],
    technologies: [
      "HTML5",
      "SCSS",
      "Ionic",
      "Typescript",
      "Firebase",
      "Jira",
      "BitBucket",
    ],
  },
  {
    name: "Sales Return Prediction System",
    links: [
      {
        label: "Repository",
        link: "https://github.com/ibrahim94ali/lfd_term_project",
      },
    ],
    info: "This project provides a predictive solution for businesses to assess whether a sale is likely to be returned, helping companies reduce operational costs. It leverages machine learning models to analyze annual sales data and predict return probabilities.",
    responsibilities: [
      "Collected and analyzed extensive sales data from Kaggle.",
      "Performed exploratory data analysis to identify patterns and insights.",
      "Cleaned and preprocessed the dataset for machine learning training.",
      "Implemented multiple machine learning models, including Linear Regression, Logistic Regression, and Random Forest.",
      "Developed a predictive solution based on trained models.",
      "Executed model training with historical data to improve accuracy.",
      "Evaluated test data and integrated predictive insights for business applications.",
      "Continuously optimized accuracy through model tuning and refinement.",
    ],
    technologies: ["Python", "NumPy", "Scikit-learn", "Kaggle"],
  },
];

const getProjects = (_, res) => {
  res.status(200).json(projects);
};

export default getProjects;
